packages:
  - "packages/*"
  - "examples/*"
patchedDependencies:
  ng-packagr: patches/ng-packagr.patch
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  simple-git-hooks: true
